import '../models/station.dart';

/// Static/demo data standing in for the government open-data feed
/// (charging station locations, operators, availability) mentioned
/// in the project brief. Replace [MockData.stations] with a real API
/// call (e.g. to data.gov.my or an operator's API) when ready.
class MockData {
  MockData._();

  static final List<ChargingStation> stations = [
    ChargingStation(
      id: 'st1',
      name: 'ChargeSini KL Sentral',
      address: 'Mid Valley, Kuala Lumpur',
      latitude: 3.1180,
      longitude: 101.6780,
      distanceKm: 1.2,
      rating: 5.0,
      reviewCount: 128,
      status: StationStatus.available,
      connectors: ['Type 2', 'CCS2'],
      speed: 'Fast',
      maxPowerKw: 60,
      pricePerKwh: 1.20,
      freeSlots: 6,
      totalSlots: 8,
      operator: 'ChargeSini',
      isOpen24Hours: true,
      amenities: ['Toilet', 'Shopping Mall', 'Cafe', 'WiFi'],
      source: StationSource.live,
      lastVerified: DateTime(2026, 7, 24, 9, 10),
    ),
    ChargingStation(
      id: 'st2',
      name: 'Gentari Pavilion',
      address: 'Pavilion KL, Bukit Bintang',
      latitude: 3.1490,
      longitude: 101.7130,
      distanceKm: 2.4,
      rating: 4.5,
      reviewCount: 76,
      status: StationStatus.busy,
      connectors: ['CHAdeMO', 'CCS2'],
      speed: 'Standard',
      maxPowerKw: 22,
      pricePerKwh: 1.10,
      freeSlots: 1,
      totalSlots: 6,
      operator: 'Gentari',
      isOpen24Hours: true,
      amenities: ['Shopping Mall', 'Restaurant', 'Toilet'],
      source: StationSource.live,
      lastVerified: DateTime(2026, 7, 24, 14, 40),
    ),
    ChargingStation(
      id: 'st3',
      name: 'Shell Recharge Rawang',
      address: 'Rawang, Selangor',
      latitude: 3.3220,
      longitude: 101.5750,
      distanceKm: 5.8,
      rating: 4.5,
      reviewCount: 41,
      status: StationStatus.available,
      connectors: ['Type 2'],
      speed: 'Slow',
      maxPowerKw: 7,
      pricePerKwh: 0.90,
      freeSlots: 4,
      totalSlots: 4,
      operator: 'Shell Recharge',
      isOpen24Hours: true,
      amenities: ['Surau', 'Toilet'],
      source: StationSource.community,
      lastVerified: DateTime(2026, 7, 23, 18, 5),
    ),
    ChargingStation(
      id: 'st4',
      name: 'Petronas EV Charger',
      address: 'KL Sentral, Kuala Lumpur',
      latitude: 3.1330,
      longitude: 101.6860,
      distanceKm: 3.1,
      rating: 4.2,
      reviewCount: 33,
      status: StationStatus.offline,
      connectors: ['CCS2'],
      speed: 'Fast',
      maxPowerKw: 50,
      pricePerKwh: 1.25,
      freeSlots: 0,
      totalSlots: 4,
      operator: 'Gentari',
      isOpen24Hours: true,
      amenities: ['Toilet', 'Restaurant'],
      source: StationSource.community,
      lastVerified: DateTime(2026, 7, 20, 8, 0),
    ),
    ChargingStation(
      id: 'st5',
      name: 'JomCharge Sunway Pyramid',
      address: 'Sunway Pyramid, Selangor',
      latitude: 3.0730,
      longitude: 101.6070,
      distanceKm: 6.4,
      rating: 4.0,
      reviewCount: 59,
      status: StationStatus.available,
      connectors: ['Type 2', 'CCS2', 'CHAdeMO'],
      speed: 'Fast',
      maxPowerKw: 120,
      pricePerKwh: 1.15,
      freeSlots: 3,
      totalSlots: 10,
      operator: 'JomCharge',
      isOpen24Hours: true,
      amenities: ['Shopping Mall', 'Cafe', 'WiFi', 'Toilet'],
      source: StationSource.live,
      lastVerified: DateTime(2026, 7, 24, 20, 15),
    ),
    ChargingStation(
      id: 'st6',
      name: 'Tesla Supercharger IOI City Mall',
      address: 'IOI City Mall, Putrajaya',
      latitude: 2.9700,
      longitude: 101.7150,
      distanceKm: 18.6,
      rating: 4.8,
      reviewCount: 22,
      status: StationStatus.available,
      connectors: ['CCS2'],
      speed: 'Fast',
      maxPowerKw: 250,
      pricePerKwh: 1.80,
      freeSlots: 8,
      totalSlots: 12,
      operator: 'Tesla',
      isOpen24Hours: true,
      amenities: ['Shopping Mall', 'Toilet', 'Restaurant', 'WiFi'],
      source: StationSource.live,
      lastVerified: DateTime(2026, 7, 24, 11, 30),
    ),
    ChargingStation(
      id: 'st7',
      name: 'TNB Electron Bangsar South',
      address: 'Bangsar South, Kuala Lumpur',
      latitude: 3.1050,
      longitude: 101.6620,
      distanceKm: 4.4,
      rating: 4.1,
      reviewCount: 17,
      status: StationStatus.available,
      connectors: ['Type 2', 'CCS2'],
      speed: 'Standard',
      maxPowerKw: 22,
      pricePerKwh: 1.00,
      freeSlots: 2,
      totalSlots: 4,
      operator: 'TNB Electron',
      isOpen24Hours: false,
      amenities: ['Toilet'],
      source: StationSource.community,
      lastVerified: DateTime(2026, 7, 22, 16, 50),
    ),
  ];

  static const List<Map<String, String>> ads = [
    {
      'title': 'Save 20% on your next charge',
      'subtitle': 'Use code GENTARI20 at any Gentari station this week.',
    },
    {
      'title': 'Pay instantly with TnG eWallet',
      'subtitle': 'Link your Touch \u2018n Go eWallet for one-tap payment.',
    },
    {
      'title': 'Refer a friend, earn RM10',
      'subtitle': 'Invite friends to EV Connect and both of you get credit.',
    },
    {
      'title': 'New: JomCharge Sunway Pyramid',
      'subtitle': '10 new fast chargers now open near you.',
    },
  ];
}
