// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS8uMl8aatvCcWfhqxZfEMREfUJYUcRPQ',
    appId: '1:325081653147:web:5b7aa4814e84eb99df8b3e',
    messagingSenderId: '325081653147',
    projectId: 'ev-connect-e6b23',
    authDomain: 'ev-connect-e6b23.firebaseapp.com',
    storageBucket: 'ev-connect-e6b23.firebasestorage.app',
    measurementId: 'G-K4P5G62FQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJo6cnQWg7ePPioGckuSggYcIFOSg7TcM',
    appId: '1:325081653147:android:1b6489e99910a7d3df8b3e',
    messagingSenderId: '325081653147',
    projectId: 'ev-connect-e6b23',
    storageBucket: 'ev-connect-e6b23.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb9uLQcMd6BeerNE-nY2P27Iuhl_wamfA',
    appId: '1:325081653147:ios:50f12bc437c57872df8b3e',
    messagingSenderId: '325081653147',
    projectId: 'ev-connect-e6b23',
    storageBucket: 'ev-connect-e6b23.firebasestorage.app',
    iosBundleId: 'com.example.evConnect',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb9uLQcMd6BeerNE-nY2P27Iuhl_wamfA',
    appId: '1:325081653147:ios:50f12bc437c57872df8b3e',
    messagingSenderId: '325081653147',
    projectId: 'ev-connect-e6b23',
    storageBucket: 'ev-connect-e6b23.firebasestorage.app',
    iosBundleId: 'com.example.evConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS8uMl8aatvCcWfhqxZfEMREfUJYUcRPQ',
    appId: '1:325081653147:web:0b9917011b0ac92fdf8b3e',
    messagingSenderId: '325081653147',
    projectId: 'ev-connect-e6b23',
    authDomain: 'ev-connect-e6b23.firebaseapp.com',
    storageBucket: 'ev-connect-e6b23.firebasestorage.app',
    measurementId: 'G-SVV50W2PXV',
  );
}
